### ISSUE TITLE
Can not skip encoding file

### ISSUE THREAD

**Issue by LItterBoy-GB** [SketchUp/rubocop-sketchup#106]
“EncryptedExtension：true“   can not skip the file (RubyEncode encoding).
## RuboCop version
0.58.1 (using Parser 2.5.1.0, running on ruby 2.2.4 x64-mingw32)

## RuboCop SketchUp version
"0.4.0"

## Config File
![image](https://user-images.githubusercontent.com/28385638/51647306-2adb4480-1fb7-11e9-90a6-a2c15a1046ef.png)

## OutPut  File
![image](https://user-images.githubusercontent.com/28385638/51647369-7261d080-1fb7-11e9-9959-dd2cfa91e88e.png)

**Comment by thomthom** [comment]
@LItterBoy-GB can you elaborate a bit more? Provide a reproducible example?

It's not clear to me how the message you highlighted in the red text relates to EncryptedExtension?

Also, "EncryptedExtension" is only relevant when you encrypt RB files into RBS or RBE files. Not if you use your own encryption. (I noticed references to RubyEncoder in your screenshot.)

**Comment by LItterBoy-GB** [comment]
I use "RubyEncoder"  to encoding my code.
I think the cop should know the encrypted files, and skip the files.

**Comment by thomthom** [comment]
The `EncryptedExtension` is a setting to allow the cops to adjust to what happens when you encrypt with RBS and RBE encryption. Other encryption methods that the extension developer implements unrelated.

As for the error you high-lighted that comes from the `SketchupRequirements/Exit` cop - and it is unrelated to encryption. It just complains about the usage of `exit` which tries to kill the Ruby interpreter.

Note that there is little value on running RuboCop on your encrypted Ruby code. It needs to run on the unencrypted Ruby code to provide any usable information.
